services:
  db:
    image: mysql:8.0
    container_name: 'ignite-call-db'
    environment:
      MYSQL_DATABASE: ignite-call
      MYSQL_USER: admin
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_ROOT_HOST: '%'

    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
volumes:
  db_data:
